[package]
name = "nib-script"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
log = "0.4.0"
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
